//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dt
{
    [Serializable]
    public class AisReportMsg : Message
    {
        public const string k_RosMessageName = "dt_msgs/AisReport";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public AisTargetMsg[] targets;

        public AisReportMsg()
        {
            this.header = new Std.HeaderMsg();
            this.targets = new AisTargetMsg[0];
        }

        public AisReportMsg(Std.HeaderMsg header, AisTargetMsg[] targets)
        {
            this.header = header;
            this.targets = targets;
        }

        public static AisReportMsg Deserialize(MessageDeserializer deserializer) => new AisReportMsg(deserializer);

        private AisReportMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.targets, AisTargetMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.targets);
            serializer.Write(this.targets);
        }

        public override string ToString()
        {
            return "AisReportMsg: " +
            "\nheader: " + header.ToString() +
            "\ntargets: " + System.String.Join(", ", targets.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
