//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dt
{
    [Serializable]
    public class AisTargetMsg : Message
    {
        public const string k_RosMessageName = "dt_msgs/AisTarget";
        public override string RosMessageName => k_RosMessageName;

        public uint mmsi;
        public byte type;
        //  Tipo da embarcação (seguindo a tabela ITU)
        public double latitude;
        public double longitude;
        public float cog;
        //  Course over ground (graus)
        public float sog;
        //  Speed over ground (nós)
        public float heading;
        //  Proa verdadeira (graus)

        public AisTargetMsg()
        {
            this.mmsi = 0;
            this.type = 0;
            this.latitude = 0.0;
            this.longitude = 0.0;
            this.cog = 0.0f;
            this.sog = 0.0f;
            this.heading = 0.0f;
        }

        public AisTargetMsg(uint mmsi, byte type, double latitude, double longitude, float cog, float sog, float heading)
        {
            this.mmsi = mmsi;
            this.type = type;
            this.latitude = latitude;
            this.longitude = longitude;
            this.cog = cog;
            this.sog = sog;
            this.heading = heading;
        }

        public static AisTargetMsg Deserialize(MessageDeserializer deserializer) => new AisTargetMsg(deserializer);

        private AisTargetMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.mmsi);
            deserializer.Read(out this.type);
            deserializer.Read(out this.latitude);
            deserializer.Read(out this.longitude);
            deserializer.Read(out this.cog);
            deserializer.Read(out this.sog);
            deserializer.Read(out this.heading);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.mmsi);
            serializer.Write(this.type);
            serializer.Write(this.latitude);
            serializer.Write(this.longitude);
            serializer.Write(this.cog);
            serializer.Write(this.sog);
            serializer.Write(this.heading);
        }

        public override string ToString()
        {
            return "AisTargetMsg: " +
            "\nmmsi: " + mmsi.ToString() +
            "\ntype: " + type.ToString() +
            "\nlatitude: " + latitude.ToString() +
            "\nlongitude: " + longitude.ToString() +
            "\ncog: " + cog.ToString() +
            "\nsog: " + sog.ToString() +
            "\nheading: " + heading.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
