//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dt
{
    [Serializable]
    public class CollisionAlertMsg : Message
    {
        public const string k_RosMessageName = "dt_msgs/CollisionAlert";
        public override string RosMessageName => k_RosMessageName;

        public uint mmsi;
        //  Identificador MMSI do alvo
        public bool collision_imminent;
        //  Indica risco de colisão com o alvo.
        public double time_to_collision;
        //  Tempo estimado até a colisão (s).
        public double closest_approach_distance;
        //  Distância mínima estimada entre o USV e o alvo (m) (-1 Indisponível)

        public CollisionAlertMsg()
        {
            this.mmsi = 0;
            this.collision_imminent = false;
            this.time_to_collision = 0.0;
            this.closest_approach_distance = 0.0;
        }

        public CollisionAlertMsg(uint mmsi, bool collision_imminent, double time_to_collision, double closest_approach_distance)
        {
            this.mmsi = mmsi;
            this.collision_imminent = collision_imminent;
            this.time_to_collision = time_to_collision;
            this.closest_approach_distance = closest_approach_distance;
        }

        public static CollisionAlertMsg Deserialize(MessageDeserializer deserializer) => new CollisionAlertMsg(deserializer);

        private CollisionAlertMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.mmsi);
            deserializer.Read(out this.collision_imminent);
            deserializer.Read(out this.time_to_collision);
            deserializer.Read(out this.closest_approach_distance);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.mmsi);
            serializer.Write(this.collision_imminent);
            serializer.Write(this.time_to_collision);
            serializer.Write(this.closest_approach_distance);
        }

        public override string ToString()
        {
            return "CollisionAlertMsg: " +
            "\nmmsi: " + mmsi.ToString() +
            "\ncollision_imminent: " + collision_imminent.ToString() +
            "\ntime_to_collision: " + time_to_collision.ToString() +
            "\nclosest_approach_distance: " + closest_approach_distance.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
