//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Dt
{
    [Serializable]
    public class WaypointArrayMsg : Message
    {
        public const string k_RosMessageName = "dt_msgs/WaypointArray";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public Sensor.NavSatFixMsg[] waypoints;

        public WaypointArrayMsg()
        {
            this.header = new Std.HeaderMsg();
            this.waypoints = new Sensor.NavSatFixMsg[0];
        }

        public WaypointArrayMsg(Std.HeaderMsg header, Sensor.NavSatFixMsg[] waypoints)
        {
            this.header = header;
            this.waypoints = waypoints;
        }

        public static WaypointArrayMsg Deserialize(MessageDeserializer deserializer) => new WaypointArrayMsg(deserializer);

        private WaypointArrayMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.waypoints, Sensor.NavSatFixMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.waypoints);
            serializer.Write(this.waypoints);
        }

        public override string ToString()
        {
            return "WaypointArrayMsg: " +
            "\nheader: " + header.ToString() +
            "\nwaypoints: " + System.String.Join(", ", waypoints.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
